import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div className='h-full flex flex-col justify-center items-center p-5'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
          <Link href='/game' className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded'>Start Game</Link>
      </main>
    </div>
  )
}
