'use client'

import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react'

export default function Home() {
  const [value, setValue] = useState('');

  return (
    <div className='h-full flex flex-col justify-center items-center p-5'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <div className='flex flex-col gap-5'>
          <Link href='/game' className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded w-full text-center'>Host Game</Link>
          <div className='flex gap-1'>
            <input className='border rounded p-1' value={value} onChange={e => setValue(e.target.value)} placeholder="Game ID" />
            <Link href={`/game?joinId=${value}`} className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded'>Join Game</Link>
          </div>
        </div>
      </main>
    </div>
  )
}
